apiVersion: v1
appVersion: 0.12.0
description: Kubernetes-Operator to simplify RBAC configurations
home: https://github.com/ckotzbauer/access-manager
keywords:
- kubernetes-operator
- operator
- rbac
- secret
maintainers:
- email: christian.kotzbauer@gmail.com
  name: ckotzbauer
name: access-manager
sources:
- https://github.com/ckotzbauer/access-manager
- https://github.com/ckotzbauer/helm-charts
version: 0.13.0
